<a href="https://colab.research.google.com/github/Ancipes/newgittest/blob/master/Lab1DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [1]:
import numpy as np
np.nonzero([1,2,3,4,0,0,7,0,8,9])

(array([0, 1, 2, 3, 6, 8, 9]),)

Question 2

In [0]:
np.random.rand(2,4,3)

array([[[0.9508751 , 0.92904139, 0.28258294],
        [0.12450221, 0.90792518, 0.7208554 ],
        [0.36052138, 0.25663468, 0.91000142],
        [0.08032011, 0.86114113, 0.89893947]],

       [[0.47256213, 0.03867524, 0.49290621],
        [0.09193366, 0.95297823, 0.31056901],
        [0.90661206, 0.92371274, 0.92936134],
        [0.91551535, 0.40521722, 0.50062076]]])

Question 3

In [0]:
x = [1,2,3,5,7,8,9]
y = [10,22,33,55,77,88,99]
z = np.polyfit(x, y, 3)
z

array([ 0.01292802, -0.22814087, 12.22340728, -1.88883309])

Question 4

In [0]:
x = 5
y = 10
x, y = y, x

Question 5

In [0]:
#Converting to Polar Coordinates
r= [[0.90402748, 0.75856483],
       [0.10793725, 0.16948372],
       [0.74821018, 0.28913789],
       [0.24983612, 0.28857679]]
def cart2pol(mat):
    converted=[]
    for x,y in mat:
        theta= np.sqrt(x**2 + y**2)
        rho=np.arctan2(y,x)
        converted.append([theta, rho])
    return converted
cart2pol(r)

[[1.1801213013534158, 0.6981289127850506],
 [0.20093576407051308, 1.0037145322934673],
 [0.8021341489360021, 0.3687618203282536],
 [0.3816996863810062, 0.8572278295237318]]

Question 6

In [0]:
r=np.array([[9, 8, 1],
       [7, 6, 8],
       [2, 2, 3]])
r = sorted(r, key=lambda a_entry: a_entry[1]) 
print (r)

[array([2, 2, 3]), array([7, 6, 8]), array([9, 8, 1])]


Question 7

In [0]:
r=np.array([[6, 7, 4, 9],
       [9, 7, 1, 7],
       [5, 0, 3, 9]])
r.reshape(2,6)

array([[6, 7, 4, 9, 9, 7],
       [1, 7, 5, 0, 3, 9]])

Question 8

In [0]:
my =np.array([[5 ,6,  7,  8,  9],
   [ 0,  1,  2,  3,  4],
   [10, 11, 12, 13, 14],
   [15 ,16 ,17, 18, 19],
   [20 ,21, 22, 23, 24]])

my[[2, 3]] = my[[3, 2]]

Question 9

In [4]:
x =  np.arange(4,13).reshape(3,3)
print(x)
print("Sum is")
print(x.sum(axis=0))


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Sum is
[21 24 27]


Question 10

In [0]:
mu,sigma=50,25
s = np.random.normal(mu, sigma, 100)
print(s)

[ 29.72015336  62.03560417  61.44697857 104.24471963  31.60345125
  19.49822806  60.59897707  10.9328772   25.66510865  12.32822256
  42.73360815  81.23110935  60.49256593  13.6940517   49.41011206
  78.24333407  76.82444984  40.8690667   66.87418042  79.7250953
  44.89009857  85.9125151  102.29706485  54.85859494  65.45741313
  45.19496336  80.84552759  85.06744972  30.83683461  70.34057582
  51.70566852  63.62923034  46.97216121   1.50268387  55.21613534
  76.66670136  67.07870966  42.51542054  42.18968106  28.78325466
  48.74467714 100.85645661  47.47604424  67.22358265  38.58523346
   4.40168107  59.71535258  86.93358349  81.03509146  50.01980937
  97.91402216  52.11624292   4.17880275   7.06076393  17.93634286
  27.15014619  51.44381746  60.68353914  21.19667061  46.04868103
  -6.87289477  85.08426956   6.90757928  23.81300543  29.96316341
   1.96202517  35.64645133  51.50646494  33.29556408  49.90663582
  59.93426933  69.89552344  46.23323019  32.20647174  82.38227705
   6.193294

Question 11

In [0]:
np.random.uniform(low=1.0, high=2.009, size=100)

array([1.12505244, 1.39029794, 1.43199533, 1.23972981, 1.91598819,
       1.43947724, 1.84582871, 1.96416979, 1.60752152, 2.00857173,
       1.67209018, 1.43951777, 1.39906703, 1.3359423 , 1.88885292,
       1.91137113, 1.82805843, 1.21340492, 1.82428649, 1.17492875,
       1.23302982, 1.867019  , 1.62946531, 1.50844783, 1.54900546,
       1.46967258, 1.55186494, 1.17747862, 1.96880532, 1.74912214,
       1.11700907, 1.29134488, 1.200381  , 1.12749583, 1.64499667,
       2.00360668, 1.64107521, 1.41719056, 1.46395863, 1.97012302,
       1.40338016, 1.27406282, 1.79640851, 1.3499264 , 1.36869908,
       1.59694193, 1.01317424, 1.71038595, 1.6834988 , 1.46254751,
       1.86069403, 1.73154101, 1.81411796, 1.09380963, 1.83089904,
       1.76945025, 1.22340392, 1.86578467, 1.30337124, 1.72071636,
       1.55962399, 1.56235276, 1.0539826 , 1.24444896, 1.50120156,
       1.74401468, 1.2377785 , 1.14062821, 1.4638342 , 1.860492  ,
       1.63810651, 1.98006706, 1.78832977, 1.54869787, 1.09234

Question 12

In [0]:
matrix=np.array([[1,2],[3,4]])
matrix=np.pad(matrix,(2,2),'constant',constant_values=4)
matrix

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 1, 2, 4, 4],
       [4, 4, 3, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

Question 13

In [0]:
X =np.array([[0.67761292, 0.25098906, 0.9896389 , 0.03984259],
       [0.43531304, 0.6484998 , 0.1093794 , 0.27807689],
       [0.94128699, 0.40438965, 0.48774248, 0.22121119],
       [0.69914384, 0.8867764 , 0.78931774, 0.61951994]])

print(X[1][1],X[1][2],X[2][1],X[2][2])

0.6484998 0.1093794 0.40438965 0.48774248


Question 14

In [0]:
x =  np.arange(4,10).reshape(2,3)
print(x)

[[4 5 6]
 [7 8 9]]


Question 15


In [0]:
x =  np.arange(4,10).reshape(2,3)
print(x)

[[4 5 6]
 [7 8 9]]
